name: 論文リポジトリセットアップ

on:
  workflow_dispatch:
    inputs:
      student_id:
        description: '学籍番号 (例: k21rs001)'
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: 学籍番号の検証
        run: |
          if [[ "${{ github.event.inputs.student_id }}" =~ k[0-9]{2}rs[0-9]{3} ]]; then
            echo "THESIS_TYPE=sotsuron" >> $GITHUB_ENV
            echo "✓ 卒業論文として設定します"
          elif [[ "${{ github.event.inputs.student_id }}" =~ k[0-9]{2}gjk[0-9]{2} ]]; then
            echo "THESIS_TYPE=thesis" >> $GITHUB_ENV
            echo "✓ 修士論文として設定します"
          else
            echo "エラー: 学籍番号の形式が正しくありません"
            exit 1
          fi
          echo "REPO_NAME=${{ github.event.inputs.student_id }}-$THESIS_TYPE" >> $GITHUB_ENV

      - name: テンプレートからリポジトリ作成
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo create "$REPO_NAME" \
            --template smkwlab/sotsuron-template \
            --private \
            --clone \
            --description "${{ github.event.inputs.student_id }}の$THESIS_TYPE"

      - name: リポジトリセットアップ
        run: |
          cd "$REPO_NAME"
          
          # 不要ファイル削除
          if [ "$THESIS_TYPE" = "sotsuron" ]; then
            rm -f thesis.tex abstract.tex
          else
            rm -f sotsuron.tex gaiyou.tex example*.tex
          fi
          
          # devcontainer追加
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/smkwlab/aldc/main/aldc)"
          
          # ブランチ構成
          git checkout -b initial-empty
          git rm -rf . || true
          git commit --allow-empty -m "初期状態"
          git push -u origin initial-empty
          
          git checkout main
          git checkout -b 0th-draft
          git push -u origin 0th-draft
          
          git checkout -b review-branch
          git push -u origin review-branch

      - name: セットアップ完了
        run: |
          echo "✅ セットアップ完了！"
          echo "リポジトリ: https://github.com/${{ github.actor }}/$REPO_NAME"
          echo ""
          echo "次の手順:"
          echo "1. リポジトリをクローン: git clone https://github.com/${{ github.actor }}/$REPO_NAME.git"
          echo "2. VS Code で開く"
          echo "3. 'Reopen in Container' を選択"