---
# Auto-assigns reviewers and PR author when PRs are opened or ready for review.
# Uses auto-assign-action and assign-author.
# Details: https://qiita.com/yusuke-sasaki/items/94a8f64e837966266bfb
name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Assignees and Reviewers to PR
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/auto_assign_myteams.yml"
      - name: Assign author to PR
        uses: technote-space/assign-author@v1
