---
name: "Run ai-reviewer"

permissions:
  pull-requests: write
  contents: read

"on":
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

# Prevent multiple reviews on rapid pushes
concurrency:
  group: ai-review-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-review:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Gemini Review Bot
        uses: toshi0806/ai-reviewer@v1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          LANGUAGE: "Japanese"
          EXCLUDE_PATHS: >-
            _build/**,deps/**,cover/**,log/**,data/**,*.tmp,*.temp
          USE_SINGLE_COMMENT_REVIEW: "true"
